### ISSUE TITLE
Setting permissions with api_login

### ISSUE THREAD

**Issue by simonh1000** [ueberauth/guardian#149]
Hi, I'm getting an error when trying to set permissions following your blog post. Can you advise?

I have this config

```
config :guardian, Guardian,
  allowed_algos: ["ES512"],
  # secret_key: fn ->
  #     {jwe, jwk} =
  #         System.get_env("MWQxoJfCxk1yTf3BQc4qJKBz/vSeehg334KHXW3x7FNe9DGVekCKKCqpTJtsKBQ/")
  #         |> JOSE.JWK.from_file(System.get_env(".jwk_file"))
  #     jwk
  #   end,
  secret_key: "********",
  issuer: "Api",
  ttl: { 30, :days },
  serializer: Api.GuardianSerializer
  # http://blog.overstuffedgorilla.com/simple-guardian-permissions/
  permissions: %{
    default: [
      :read_token,
      :revoke_token
    ],
    admin: [
      :full
    ]
  }
```
and this controller
```
  def create(conn, %{"username" => email, "password" => password}) do
      case Auth.login_by_username_and_pass(conn, email, password, repo: Repo) do
          {:ok, conn} ->
            user = conn.assigns[:current_user]

            perms =
              case user.customer_id == 1 do  # checks Admin User
                true -> %{default: Guardian.Permissions.max, admin: Guardian.Permissions.max}
                false -> %{default: Guardian.Permissions.max}
              end

            new_conn = Guardian.Plug.api_sign_in(conn, user, perms: perms)
            ...
```
but am getting this error

```
[error] #PID<0.653.0> running MosaicApi.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /sessions
** (exit) an exception was raised:
    ** (Poison.EncodeError) unable to encode value: {:perms, %{admin: -1, default: -1}}
        (jose) lib/jose/poison/ord_encoder.ex:123: JOSE.Poison.OrdEncoder.Any.encode/2
        (jose) lib/jose/poison/ord_encoder.ex:73: anonymous fn/3 in JOSE.Poison.OrdEncoder.List.encode/3
        (jose) lib/jose/poison/ord_encoder.ex:74: JOSE.Poison.OrdEncoder.List.encode/3
        (jose) lib/jose/poison/ord_encoder.ex:56: anonymous fn/4 in JOSE.Poison.OrdEncoder.Map.encode/3
        (jose) lib/jose/poison/ord_encoder.ex:57: JOSE.Poison.OrdEncoder.Map."-encode/3-lists^foldr/2-0-"/3
        (jose) lib/jose/poison/ord_encoder.ex:57: JOSE.Poison.OrdEncoder.Map.encode/3
        (jose) lib/jose/poison.ex:6: JOSE.Poison.ord_encode!/2
        (jose) src/jose_jwt.erl:89: :jose_jwt.to_binary/1
        (jose) src/jose_jwt.erl:170: :jose_jwt.sign/3
        lib/guardian.ex:303: Guardian.encode_claims/1
        lib/guardian.ex:94: Guardian.encode_from_hooked/1
        lib/guardian/plug.ex:179: Guardian.Plug.api_sign_in/4
        (mosaic_api) web/controllers/session_controller.ex:25: Api.SessionController.create/2
```

**Comment by hassox** [comment]
@simonh1000 You'll need to make the call to `Guardian.Plug.sign_in` with a map for the permissions.

```
new_conn = Guardian.Plug.api_sign_in(conn, user, %{perms: perms})
```
