### ISSUE TITLE
Exclude some controller actions from authentication with Guardian.Plug.EnsureAuthenticated.

### ISSUE THREAD

**Issue by ospaarmann** [ueberauth/guardian#180]
It would be great if one could exclude some controller actions from authentication when using Guardian.Plug.EnsureAuthenticated. For example in a UserController which also handles signups on the create action. I don't want it to be protected. Creating a special SignupController seems like a not so nice idea.

Something like this would be great:

```
defmodule MyApp.UserController do
  use MyApp.Web, :controller
  alias MyApp.User

  # Current way
  plug Guardian.Plug.EnsureAuthenticated, handler: MyApp.ErrorController

  # Something like this would be nice:
  plug Guardian.Plug.EnsureAuthenticated, handler: MyApp.ErrorController, except: [:create, :new]

  plug :scrub_params, "data" when action in [:create, :update]

  def create(conn, %{"data" => %{"attributes" => user_params}}) do
    changeset = User.registration_changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, user} ->
        conn
        |> put_status(:created)
        |> render("show.json", user: user)
      {:error, changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> render(MyApp.ChangesetView, "error.json", changeset: changeset)
    end
  end

  def index(conn, _params) do
    users = Repo.all(User)
    render conn, users: users
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get(User, id)
    render conn, user: user
  end
end
```

**Comment by AlejandroHuerta** [comment]
This took me a while to figure out myself but you can write it this way:

`plug Guardian.Plug.EnsureAuthenticated, [handler: MyApp.SessionController] when not action in [:create, :new]`

**Comment by doomspork** [comment]
@AlejandroHuerta that's a good point.  That is almost certainly a more Elixir way of doing it.

**Comment by AlejandroHuerta** [comment]
I should also add that what I posted works right now. @doomspork

**Comment by doomspork** [comment]
@AlejandroHuerta right 😀  I've been working in Ruby too much lately and spaced on guards, thank you for saying something!  Guard is the more appropriate way to do this.

**Comment by hopewise** [comment]
Writing in this way:

    plug Guardian.Plug.EnsureAuthenticated, [handler: MyApp.SessionController] when not action in [:create, :new]

I got error:

```
== Compilation error on file web/router.ex ==
** (CompileError) web/router.ex:16: undefined function when/2
    (elixir) expanding macro: Kernel.@/1
    web/router.ex:16: Trackware.Router (module)
    (elixir) expanding macro: Kernel.if/2
    web/router.ex:16: Trackware.Router (module)
    (phoenix) expanding macro: Phoenix.Router.plug/2
    web/router.ex:16: Trackware.Router (module)
    (phoenix) expanding macro: Phoenix.Router.pipeline/2
    web/router.ex:12: Trackware.Router (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by anildigital** [comment]
👍
