### ISSUE TITLE
Elixir 1.3.2 compiler errors

### ISSUE THREAD

**Issue by adsteel** [ueberauth/guardian#189]
When I try to compile 0.12 with Elixir 1.3.2, in a Phoenix 1.2 app, I get two errors:

```bash
$ mix deps.compile guardian
==> guardian
Compiling 20 files (.ex)
warning: the variable "handler" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/guardian/plug/ensure_permissions.ex:53

warning: the variable "opts_map" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/guardian/plug/verify_header.ex:46


== Compilation error on file lib/guardian.ex ==
** (RuntimeError) Guardian is not configured
    lib/guardian.ex:26: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

could not compile dependency :guardian, "mix compile" failed. You can recompile this dependency with "mix deps.compile guardian", update it with "mix deps.update guardian" or clean it with "mix deps.clean guardian"
```

**Comment by adsteel** [comment]
Derp. Still learning to read the messages. This is not a bug it seems.

**Comment by Faolain** [comment]
how did you solve this?

**Comment by adsteel** [comment]
This part of the error message was where the issue was:

```
** (RuntimeError) Guardian is not configured
    lib/guardian.ex:26: (module)
```

I configured Guardian according to the docs and everything worked fine.

**Comment by Angarsk8** [comment]
I'm experiencing the same issue and I'm sure I configured Guardian according to the docs. This is happening after running `mix docker.build` to build a docker image using the `mix_docker` package.

This is the error I'm getting:

```
== Compilation error on file lib/guardian.ex ==
** (RuntimeError) Guardian is not configured
    lib/guardian.ex:26: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

could not compile dependency :guardian, "mix compile" failed. You can recompile this dependency with "mix deps
.compile guardian", update it with "mix deps.update guardian" or clean it with "mix deps.clean guardian"
The command '/bin/sh -c mix do deps.get, deps.compile' returned a non-zero code: 1
** (MatchError) no match of right hand side value: {%IO.Stream{device: :standard_io, line_or_bytes: :line, raw
: false}, 1}
    lib/mix_docker.ex:153: MixDocker.system!/2
    lib/mix_docker.ex:123: MixDocker.with_dockerfile/2
    lib/mix_docker.ex:18: MixDocker.build/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Does anyone has experienced this problem using `mix_docker` for building docker images and generating releases?

Thanks,
