### ISSUE TITLE
UUID as primary key breaks Poison encoding

### ISSUE THREAD

**Issue by whitepaperclip** [ueberauth/guardian#206]
From Phoenix (1.2.1) logs:

```
INSERT INTO "users" ("email","encrypted_password","first_name","last_name","sign_in_count","username","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING "id" ["nick@whitepaperclip.com", "$2b$12$FgJM8C7HkcSvaD9RbxM1gewUnOZFMYWRfJ.qJQqRB3US6YuL0Kuqq", "Nick", "K", 0, "nkezhaya", {{2016, 9, 21}, {16, 45, 2, 0}}, {{2016, 9, 21}, {16, 45, 2, 0}}]
[debug] QUERY OK db=1.0ms
commit []
[info] Sent 500 in 496ms
[error] #PID<0.584.0> running MyApp.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /auth/register
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Poison.Encoder.BitString.chunk_size/3
        (poison) lib/poison/encoder.ex:127: Poison.Encoder.BitString.chunk_size(<<216, 230, 130, 65, 203, 183, 76, 195, 164, 130, 199, 16, 41, 48, 69, 144>>, nil, 5)
        (poison) lib/poison/encoder.ex:122: Poison.Encoder.BitString.escape/2
        (poison) lib/poison/encoder.ex:84: Poison.Encoder.BitString.encode/2
        (jose) lib/jose/poison/lexical_encoder.ex:129: anonymous fn/4 in JOSE.Poison.LexicalEncoder.Map.encode/3
        (jose) lib/jose/poison/lexical_encoder.ex:130: JOSE.Poison.LexicalEncoder.Map."-encode/3-lists^foldr/2-0-"/3
        (jose) lib/jose/poison/lexical_encoder.ex:130: JOSE.Poison.LexicalEncoder.Map.encode/3
        (jose) lib/jose/poison.ex:6: JOSE.Poison.lexical_encode!/2
        (jose) src/jose_jwt.erl:89: :jose_jwt.to_binary/1
        (jose) src/jose_jwt.erl:170: :jose_jwt.sign/3
        lib/guardian.ex:303: Guardian.encode_claims/1
        lib/guardian.ex:94: Guardian.encode_from_hooked/1
        lib/guardian/plug.ex:179: Guardian.Plug.api_sign_in/4
        ...
```

**Comment by whitepaperclip** [comment]
Never mind! Anyone else who encounters this:

`@primary_key {:id, :binary_id, []}` should go *on top of*

`schema "users" do`
