### ISSUE TITLE
** (RuntimeError) No secret key configured for JWT

### ISSUE THREAD

**Issue by MartinElvar** [ueberauth/guardian#387]
Been struggling on this for some hours now, i've properly mis-configured somehow, somewhere, but i can't put eye on the errors.

Basically i'm getting the error in the title, even tho. the secret key is specified in my configuration.

```Elixir
config :splish, SplishWeb.AuthPipeline,
  issuer: "splish",
  secret_key: "secret",
  module: SplishWeb.Guardian,
  error_handler: SplishWeb.AuthErrorHandler
```

But when i run my test i get the following error message.

```
  6) test delete user deletes chosen user (SplishWeb.UserControllerTest)
     test/splish_web/controllers/user_controller_test.exs:69
     ** (RuntimeError) No secret key configured for JWT
     stacktrace:
       (guardian) lib/guardian/token/jwt.ex:317: Guardian.Token.Jwt.fetch_secret/2
       (guardian) lib/guardian/token/jwt.ex:162: Guardian.Token.Jwt.create_token/3
       (guardian) lib/guardian.ex:721: Guardian.returning_tuple/1
       (guardian) lib/guardian.ex:556: Guardian.encode_and_sign/4
       (guardian) lib/guardian/plug.ex:179: Guardian.Plug.sign_in/5
       (splish) test/support/auth_helper.ex:9: Splish.Test.AuthHelper.authorize/1
       test/splish_web/controllers/user_controller_test.exs:11: SplishWeb.UserControllerTest.__ex_unit_setup_1/1
       test/splish_web/controllers/user_controller_test.exs:1: SplishWeb.UserControllerTest.__ex_unit__/2
```
I even tried to run ```IO.inspect Application.get_env(:splish, SplishWeb.AuthPipeline)``` in my test, and i get the following output.

```
[issuer: "splish",
 secret_key: "secret",
 module: SplishWeb.Guardian, error_handler: SplishWeb.AuthErrorHandler]
```

Which seems sane, what am i missing?

**Comment by MartinElvar** [comment]
Fixed this by supplying 2x config maps, as such.

```elixir
config :splish, SplishWeb.Guardian,
  issuer: "splish",
  secret_key: "secret"

config :splish, SplishWeb.AuthPipeline,
  module: SplishWeb.Guardian,
  error_handler: SplishWeb.AuthErrorHandler
```

Don't know if this is the right approach, but it seem to work.
