### ISSUE TITLE
Guardian 1.0.0-beta1 doesn't compile without Plug

### ISSUE THREAD

**Issue by rbino** [ueberauth/guardian#402]
Steps to reproduce:
- `mix new tmp`
- Add `{:guardian, "~> 1.0.0-beta.1"}` to `mix.exs`
- `mix deps.get && mix.compile`
```
== Compilation error in file lib/guardian/permissions/bitwise.ex ==
** (CompileError) lib/guardian/permissions/bitwise.ex:367: module Plug.Conn is not loaded and could not be found
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
    (elixir) expanding macro: Kernel.if/2
could not compile dependency :guardian, "mix compile" failed. You can recompile this dependency with "mix deps.compile guardian", update it with "mix deps.update guardian" or clean it with "mix deps.clean guardian"
```

This happens because `import Plug.Conn` is expanded even if it's inside a false conditional. You can verify this with this

```
$ cat example.ex
defmodule TestPlug do
  if false do
    import Plug.Conn
  end
end
$ elixirc example.ex 
== Compilation error in file defmodule_then_if.ex ==
** (CompileError) example.ex:3: module Plug.Conn is not loaded and could not be found
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (elixir) expanding macro: Kernel.if/2
```

**Comment by doomspork** [comment]
Thank you for the report @rbino!  We'll look into this 👍

**Comment by doomspork** [comment]
@rbino looks like we've already got a PR staged for this ( #397 ) so I'm going to close and cut a new release today 👍

**Comment by rbino** [comment]
That PR didn't fix the issue, I've just tried it by using the github version and the compilation still fails without Plug. I've opened #404 that should fix the issue.
