### ISSUE TITLE
use 1.0-beta Got  undefined function find_me_a_resource

### ISSUE THREAD

**Issue by zhulinpinyu** [ueberauth/guardian#414]
```elixir
defmodule MyApp.Guardian do
  use Guardian, otp_app: :my_app

  def subject_for_token(resource, _claims) do
    {:ok, to_string(resource.id)}
  end

  def subject_for_token(_, _) do
    {:error, :reason_for_error}
  end

  def resource_from_claims(claims) do
    {:ok, find_me_a_resource(claims["sub"])}
  end
  def resource_from_claims(_claims) do
    {:error, :reason_for_error}
  end
end
```

{:guardian, "~> 1.0-beta"}

**Comment by yordis** [comment]
@zhulinpinyu could you put the stack trace? With that people outside of guardian team could take a look faster because we do not know the code base but reading the stack trace we can figure out faster.

**Comment by zhulinpinyu** [comment]
```
➜  demoJWT mix phx.server
Compiling 17 files (.ex)

== Compilation error in file lib/demoJWT/guardian.ex ==
** (CompileError) lib/demoJWT/guardian.ex:13: undefined function find_me_a_resource/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by yordis** [comment]
@zhulinpinyu ahhhhhh I see what is the problem

`find_me_a_resource` is not a function from Guardian, the point is that you replaced `find_me_a_resource` with some function from your logic, which could take what comes from `claims["sub"]` and return the resource back. You could do the business logic in that function as well but I wouldn't.

```
 def resource_from_claims(claims) do
    resource = MyApp.get_resource_from_claims(claims["sub"])
    # Do whatever you want but you have to return `{:ok, resource}`
    {:ok,  resource}
  end
```

**Comment by doomspork** [comment]
@yordis is correct, you're referencing a function that does not exist.  Thanks for helping out @yordis ❤️

**Comment by zhulinpinyu** [comment]
@yordis  thanks you much.

```elixir
def resource_from_claims(claims) do
  user = Accounts.get_user!(claims["sub"])
  {:ok, user}
end
```

**Comment by alec-c4** [comment]
Lads, could you add it to documentation?

**Comment by yordis** [comment]
@doomspork I would use this snippet

```elixir
def resource_from_claims(claims) do
    resource = MyApp.get_resource_from_claims(claims["sub"])
    # Do whatever you want but you have to return `{:ok, resource}`
    {:ok,  resource}
  end
```

At least they can relate `MyApp` and the breaking down of `{:ok, resource}`

**Comment by doomspork** [comment]
@yordis if you'd like to open a PR to update the docs with that snippet go for it 👍

**Comment by yordis** [comment]
@doomspork done
