### ISSUE TITLE
function nil.peek/2 is undefined or private

### ISSUE THREAD

**Issue by rafbgarcia** [ueberauth/guardian#428]
Just started using Guardian and am facing this issue when attempting to revoke a token.

It says the issue is [in this line](https://github.com/ueberauth/guardian/blob/master/lib/guardian.ex#L664).

(image is clearer, but code is below fwiw)

<img width="1360" alt="2__iex_-s_mix_phx_server" src="https://user-images.githubusercontent.com/1904314/33227195-cd2f7daa-d184-11e7-8e62-aab30e20e0ce.png">

```ex
pry(6)> token
"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhcGkiLCJleHAiOjE1MTM5OTc5MzUsImlhdCI6MTUxMTU3ODczNSwiaXNzIjoiYXBpIiwianRpIjoiMmJhNDdiZjEtZTY1Ni00YTFkLTg1ZTctZmI1ODAxYzk3ZmY0IiwibmJmIjoxNTExNTc4NzM0LCJzdWIiOiIyIiwidHlwIjoiYWNjZXNzIn0.78Mr2uBCddb5eBt1tHcXhR2Xebx98sjfh-yvE55l2nAeALtse93CBHC3aUQmJHmPLC_w07vCPaNuoy4D9guqzA"
pry(7)> Api.Guardian.decode_and_verify(token)
{:ok,
 %{"aud" => "api", "exp" => 1513997935, "iat" => 1511578735, "iss" => "api",
   "jti" => "2ba47bf1-e656-4a1d-85e7-fb5801c97ff4", "nbf" => 1511578734,
   "sub" => "2", "typ" => "access"}}
pry(8)> Api.Guardian.revoke(token)
** (UndefinedFunctionError) function nil.peek/2 is undefined or private
    nil.peek(Api.Guardian, "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhcGkiLCJleHAiOjE1MTM5OTc5MzUsImlhdCI6MTUxMTU3ODczNSwiaXNzIjoiYXBpIiwianRpIjoiMmJhNDdiZjEtZTY1Ni00YTFkLTg1ZTctZmI1ODAxYzk3ZmY0IiwibmJmIjoxNTExNTc4NzM0LCJzdWIiOiIyIiwidHlwIjoiYWNjZXNzIn0.78Mr2uBCddb5eBt1tHcXhR2Xebx98sjfh-yvE55l2nAeALtse93CBHC3aUQmJHmPLC_w07vCPaNuoy4D9guqzA")
    (guardian) lib/guardian.ex:664: Guardian.revoke/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (iex) lib/iex/evaluator.ex:231: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:212: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:190: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:89: IEx.Evaluator.loop/1
    (iex) lib/iex/evaluator.ex:24: IEx.Evaluator.init/4
    (iex) lib/iex/pry.ex:55: IEx.Pry.pry/2
    (api) lib/central/resolve/logout.ex:4: Central.Resolve.Logout.logout/2
    (absinthe) lib/absinthe/resolution.ex:187: Absinthe.Resolution.call/2
    (absinthe) lib/absinthe/phase/document/execution/resolution.ex:187: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
    (absinthe) lib/absinthe/phase/document/execution/resolution.ex:149: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4
    (absinthe) lib/absinthe/phase/document/execution/resolution.ex:135: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
    (absinthe) lib/absinthe/phase/document/execution/resolution.ex:71: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
    (absinthe) lib/absinthe/phase/document/execution/resolution.ex:53: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
    (absinthe) lib/absinthe/phase/document/execution/resolution.ex:25: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
    (absinthe) lib/absinthe/pipeline.ex:253: Absinthe.Pipeline.run_phase/3
    (absinthe_plug) lib/absinthe/plug.ex:358: Absinthe.Plug.run_query/3
```

**Comment by yordis** [comment]
https://github.com/ueberauth/guardian/blob/master/lib/guardian.ex#L393 
For some reason `config(:token_module)` is giving `nil` back

**Comment by yordis** [comment]
@rafbgarcia could you please check your config and see what you have on ` token_module` key

**Comment by rafbgarcia** [comment]
@yordis nothing..

```ex

config :api, Api.Guardian,
  issuer: "api",
  secret_key: "SL6xJHKeZRRr/2YOJpLW2KvWTjh3h0IZ4UPUjPqGXX9J3fXrfSUxhgw2zXeoaXvt"
```

**Comment by yordis** [comment]
I found the issue. We are not falling back to the default

`token_mod = apply(mod, :config, [:token_module, @default_token_module])` This is normally how we should read the `token_mod`

**Comment by yordis** [comment]
@rafbgarcia do me a favor please, change this function

```elixir
def peek(token) do
  config(:token_module).peek(__MODULE__, token)
end
```

to

```elixir
def peek(token) do
  config(:token_module, @default_token_module).peek(__MODULE__, token)
end
```

That is the actual fix

**Comment by rafbgarcia** [comment]
@yordis I saw your PR, do you still want me to do that?

**Comment by yordis** [comment]
@rafbgarcia I am doing more than just changing that line. I will handle it, I just wanna you to confirmed because you had the environment for it

**Comment by rafbgarcia** [comment]
Just tested it, I can confirm it works @yordis, thanks
